### PR TITLE
use unicode type, fix string writing

### PR DESCRIPTION
**Pull request by esheldon**
Use 'U' instead of 'S' for strings

remove code that tried to decode object to utf-8, which
is not needed

### CODE REVIEW

**Comment by esheldon** [comment]
This also contains a fix for python3 in a test.

I ran the tests and all worked except the connect test, which uses exc_info in a way that doesn't work on python 3.

**Comment by esheldon** [comment]
shall we merge this and defer the continuous integration?

**Comment by manning-ncsa** [comment]
Sure, if you are confident in the update then we can merge. I'll then need to make a new release and update [the pip repo](https://pypi.org/project/easyaccess/). Is this a backwards-compatible change? (i.e. should it be `1.4.11` or `1.5.0`?)

**Comment by esheldon** [comment]
I am not confident because we don't have CI set up, and I'm not sure how many have tested this in the wild.

**Comment by beckermr** [comment]
I ran this query:

```
select
    m.tilename || '-' || m.band as key,
    m.tilename as tilename,
    fai.path as path,
    fai.filename as filename,
    fai.compression as compression,
    m.band as band,
    m.pfw_attempt_id as pfw_attempt_id
from
    prod.proctag t,
    prod.coadd m,
    prod.file_archive_info fai
where
    t.tag='Y6A2_COADD'
    and t.pfw_attempt_id=m.pfw_attempt_id
    and m.filetype='coadd'
    and fai.filename=m.filename
    and fai.archive_name='desar2home'; > data.csv
```

and got this table back:

```
KEY,TILENAME,PATH,FILENAME,COMPRESSION,BAND,PFW_ATTEMPT_ID
DES0011+0252-Y,DES0011+0252,OPS/multiepoch/Y6A1/r4907/DES0011+0252/p01/coadd,DES0011+0252_r4907p01_Y.fits,.fz,Y,2763804
DES0238-1124-g,DES0238-1124,OPS/multiepoch/Y6A1/r4931/DES0238-1124/p01/coadd,DES0238-1124_r4931p01_g.fits,.fz,g,2839078
DES0256-3749-z,DES0256-3749,OPS/multiepoch/Y6A1/r4931/DES0256-3749/p01/coadd,DES0256-3749_r4931p01_z.fits,.fz,z,2840010
DES0147-1541-z,DES0147-1541,OPS/multiepoch/Y6A1/r4920/DES0147-1541/p01/coadd,DES0147-1541_r4920p01_z.fits,.fz,z,2833782
DES0115-2458-i,DES0115-2458,OPS/multiepoch/Y6A1/r4907/DES0115-2458/p01/coadd,DES0115-2458_r4907p01_i.fits,.fz,i,2805981
DES0110-4414-Y,DES0110-4414,OPS/multiepoch/Y6A1/r4907/DES0110-4414/p01/coadd,DES0110-4414_r4907p01_Y.fits,.fz,Y,2805882
DES0223-1915-Y,DES0223-1915,OPS/multiepoch/Y6A1/r4920/DES0223-1915/p01/coadd,DES0223-1915_r4920p01_Y.fits,.fz,Y,2835141
DES0613-4414-i,DES0613-4414,OPS/multiepoch/Y6A1/r4939/DES0613-4414/p01/coadd,DES0613-4414_r4939p01_i.fits,.fz,i,2852050
DES0224-2706-r,DES0224-2706,OPS/multiepoch/Y6A1/r4920/DES0224-2706/p01/coadd,DES0224-2706_r4920p01_r.fits,.fz,r,2836059
DES0539-3123-z,DES0539-3123,OPS/multiepoch/Y6A1/r4939/DES0539-3123/p01/coadd,DES0539-3123_r4939p01_z.fits,.fz,z,2852748
DES0248-0041-i,DES0248-0041,OPS/multiepoch/Y6A1/r4931/DES0248-0041/p01/coadd,DES0248-0041_r4931p01_i.fits,.fz,i,2839228
DES0449-1915-z,DES0449-1915,OPS/multiepoch/Y6A1/r4939/DES0449-1915/p01/coadd,DES0449-1915_r4939p01_z.fits,.fz,z,2850170
DES0445-2706-g,DES0445-2706,OPS/multiepoch/Y6A1/r4939/DES0445-2706/p01/coadd,DES0445-2706_r4939p01_g.fits,.fz,g,2849185
DES0138-6456-z,DES0138-6456,OPS/multiepoch/Y6A1/r4920/DES0138-6456/p02/coadd,DES0138-6456_r4920p02_z.fits,.fz,z,2837931
DES0118-2958-i,DES0118-2958,OPS/multiepoch/Y6A1/r4907/DES0118-2958/p01/coadd,DES0118-2958_r4907p01_i.fits,.fz,i,2806041
DES0251+0126-Y,DES0251+0126,OPS/multiepoch/Y6A1/r4931/DES0251+0126/p01/coadd,DES0251+0126_r4931p01_Y.fits,.fz,Y,2839275
DES0231-1624-Y,DES0231-1624,OPS/multiepoch/Y6A1/r4920/DES0231-1624/p01/coadd,DES0231-1624_r4920p01_Y.fits,.fz,Y,2835263
DES0235-2249-Y,DES0235-2249,OPS/multiepoch/Y6A1/r4920/DES0235-2249/p01/coadd,DES0235-2249_r4920p01_Y.fits,.fz,Y,2838878
DES0628-4831-r,DES0628-4831,OPS/multiepoch/Y6A1/r4939/DES0628-4831/p01/coadd,DES0628-4831_r4939p01_r.fits,.fz,r,2851049
DES0411-6414-i,DES0411-6414,OPS/multiepoch/Y6A1/r4939/DES0411-6414/p02/coadd,DES0411-6414_r4939p02_i.fits,.fz,i,2852190
DES0156-4457-r,DES0156-4457,OPS/multiepoch/Y6A1/r4920/DES0156-4457/p01/coadd,DES0156-4457_r4920p01_r.fits,.fz,r,2835809
DES0157-1832-Y,DES0157-1832,OPS/multiepoch/Y6A1/r4920/DES0157-1832/p01/coadd,DES0157-1832_r4920p01_Y.fits,.fz,Y,2834865
DES0548-5414-z,DES0548-5414,OPS/multiepoch/Y6A1/r4939/DES0548-5414/p01/coadd,DES0548-5414_r4939p01_z.fits,.fz,z,2852885
DES0306-5123-Y,DES0306-5123,OPS/multiepoch/Y6A1/r4931/DES0306-5123/p01/coadd,DES0306-5123_r4931p01_Y.fits,.fz,Y,2840164
DES0555-2832-z,DES0555-2832,OPS/multiepoch/Y6A1/r4939/DES0555-2832/p01/coadd,DES0555-2832_r4939p01_z.fits,.fz,z,2850951
DES0049+0418-r,DES0049+0418,OPS/multiepoch/Y6A1/r4907/DES0049+0418/p01/coadd,DES0049+0418_r4907p01_r.fits,.fz,r,2764124
DES0604-3415-r,DES0604-3415,OPS/multiepoch/Y6A1/r4939/DES0604-3415/p01/coadd,DES0604-3415_r4939p01_r.fits,.fz,r,2852015
```

etc etc.

**Comment by beckermr** [comment]
My machine was using python 3.10. 

Is this test good enough @esheldon?

**Comment by esheldon** [comment]
Thanks Matt, that's a nice data point.

**Comment by beckermr** [comment]
Awesome. I'd say we merge.

**Comment by esheldon** [comment]
How many people use this for their daily work?  Is it 3, 10, 100?  If it is a large number then I think we need more tests.

**Comment by esheldon** [comment]
I say this because we have no CI testing to fall back on

**Comment by beckermr** [comment]
I'm sure a lot of people use. It's broken either way for current pythons so I don't see the point in worrying over tests.

**Comment by beckermr** [comment]
Getting the tests to run in CI is going to be a nightmare: https://github.com/beckermr/easyaccess/actions/runs/3089242871

I'm pretty sure we shouldn't be spending time here.

**Comment by beckermr** [comment]
If we do want tests, we'll need a machine user account for testing.

**Comment by esheldon** [comment]
I vote we merge this, we've waited long enough for feedback.

**Comment by manning-ncsa** [comment]
Now you can place blame squarely on me if downstream code breaks. On the other hand, it may teach people a valuable lesson in locking the versions of their dependencies. Speaking of which, this seems to be a backwards-compatible bug fix, so I will create a release `1.4.11` as [suggested above](https://github.com/des-labs/easyaccess/pull/6#issuecomment-1247053935) unless someone protests.

I do not see a reason for me to update DESaccess to use this new version, so let me know if you do.

**Comment by esheldon** [comment]
The most visible change is it fixes a bug in the printout for strings when writing to a text file, e.g. `.... ; > output.tab`

I don't know what DESaccess is doing.  If DESaccess is not using that then there is no need to update.

**Comment by manning-ncsa** [comment]
Published new version for pip: https://pypi.org/project/easyaccess/1.4.11/
New release published on GitHub: https://github.com/des-labs/easyaccess/releases/tag/1.4.11

Can someone install and test 1.4.11 via pip?

**Pull request merged**
